baseURL = 'https://guides.spatiosoft.com/'
languageCode = 'en-us'
title = 'SPATIOSOFT Guides'
theme = 'soho'
mainSections = ["pages"]
publishDir =  'docs'

[params]
    author = "SPATIOSOFT"
    description = "List of guides edited by SPATIOSOFT"
    copyright = "SPATIOSOFT"
    profilePicture = "logo500.png"

[menu]

    [[menu.main]]
    name = "Overview Of Software Development"
    weight = 100
    identifier = "software-development"
    url = "https://guides.spatiosoft.com/overview-of-software-development/"

